"""Generate ready-to-apply blocking rules for attacking IPs (defensive mitigation).

Talos never executes firewall changes on the host — that needs root and can
lock you out of your own box. Instead it emits copy-paste / downloadable rules for
the common tools (fail2ban, iptables, ufw, Windows firewall) so a human can review
and apply them.
"""
from __future__ import annotations


def _valid_ips(ips) -> list[str]:
    out, seen = [], set()
    for ip in ips or []:
        parts = str(ip).strip().split(".")
        if len(parts) == 4 and all(p.isdigit() and 0 <= int(p) <= 255 for p in parts):
            s = ".".join(parts)
            if s not in seen:
                seen.add(s)
                out.append(s)
    return out


def _fail2ban_jail(threshold: int) -> str:
    return (
        "# /etc/fail2ban/jail.local — generated by Talos\n"
        "[sshd-talos]\n"
        "enabled  = true\n"
        "port     = ssh\n"
        "filter   = sshd\n"
        "logpath  = %(sshd_log)s\n"
        f"maxretry = {threshold}\n"
        "findtime = 600\n"
        "bantime  = 3600\n"
    )


def build_mitigation(ips, threshold: int = 5) -> dict:
    ips = _valid_ips(ips)
    if not ips:
        return {"error": "No valid IPv4 addresses to block.", "ip_count": 0, "ips": []}
    return {
        "ip_count": len(ips),
        "ips": ips,
        "fail2ban_jail": _fail2ban_jail(threshold),
        "fail2ban_commands": "\n".join(
            f"fail2ban-client set sshd-talos banip {ip}" for ip in ips),
        "iptables": "\n".join(f"iptables -A INPUT -s {ip} -j DROP" for ip in ips),
        "ufw": "\n".join(f"ufw deny from {ip}" for ip in ips),
        "windows_firewall": "\n".join(
            f'netsh advfirewall firewall add rule '
            f'name="Talos block {ip}" dir=in action=block remoteip={ip}'
            for ip in ips),
        "blocklist": "\n".join(ips),
        "note": "Review before applying — blocking your own IP can lock you out. "
                "Talos generates these rules but never runs them for you.",
    }
