import { ResourceDecorator as Resource, ExecutionContext } from '@nitrostack/core';
import { callTalosTool } from './talos.bridge.js';

export class TalosResources {
  @Resource({
    uri: 'talos://overview',
    name: 'Talos MCP Overview',
    title: 'Talos MCP Overview',
    description: 'Overview of the Talos MCP server, safety posture, transports, and tool groups.',
    mimeType: 'application/json',
    annotations: {
      audience: ['user', 'assistant'],
      priority: 1,
    },
  })
  async overview(uri: string, ctx: ExecutionContext) {
    ctx.logger.info('Fetching Talos MCP overview');

    return {
      uri,
      name: 'talos-mcp-server',
      purpose: 'Expose the Talos AI Security Assistant and brute-force detector as MCP tools.',
      safety: 'Passive scanning and defensive analysis only. Scan targets only with authorization.',
      transports: {
        local: 'STDIO',
        hosted: 'HTTP/SSE via NitroStack dual transport',
        basePath: process.env.MCP_BASE_PATH || '/mcp',
        defaultPort: process.env.PORT || process.env.MCP_PORT || '3002',
      },
      toolGroups: [
        'website scanning',
        'phishing and link safety detection',
        'CVE lookup',
        'auth log brute-force analysis',
        'research paper and citation search',
        'security report generation',
        'defensive mitigation generation',
        'explicit email and alert delivery',
        'runtime self-test',
        'password/hash/JWT/IP utilities',
        'Talos security toolbox',
        'resource library search',
      ],
      reportPolicy: 'generate_security_report returns and saves reports only by default. Use send_report_email or send_email only when the user explicitly asks to email, send, forward, or share.',
      researchPolicy: 'When the user asks for research papers, academic papers, citations, studies, references, or literature, call find_research_papers or search_research instead of answering from memory.',
      linkSafetyPolicy: 'When the user asks if a link is safe, phishing, scam, malicious, suspicious, or okay to open, call analyze_link_safety.',
    };
  }

  @Resource({
    uri: 'talos://security-tools',
    name: 'Talos Security Tool Catalog',
    title: 'Talos Security Tool Catalog',
    description: 'Compact category summary for Talos built-in security tools.',
    mimeType: 'application/json',
    annotations: {
      audience: ['assistant'],
      priority: 0.8,
    },
  })
  async securityTools(uri: string, ctx: ExecutionContext) {
    const catalog = await callTalosTool('list_security_tools', {}, ctx);

    return {
      uri,
      catalog,
    };
  }

  @Resource({
    uri: 'talos://resources',
    name: 'Talos Resource Library',
    title: 'Talos Resource Library',
    description: 'Books and documents available to Talos resource-search tools.',
    mimeType: 'application/json',
    annotations: {
      audience: ['assistant'],
      priority: 0.7,
    },
  })
  async resources(uri: string, ctx: ExecutionContext) {
    const resources = await callTalosTool('list_resources', {}, ctx);

    return {
      uri,
      resources,
    };
  }

  @Resource({
    uri: 'talos://last-report',
    name: 'Latest Talos Security Report',
    title: 'Latest Talos Security Report',
    description: 'Most recent report generated by generate_security_report, if one exists.',
    mimeType: 'application/json',
    annotations: {
      audience: ['assistant'],
      priority: 0.75,
    },
  })
  async lastReport(uri: string, ctx: ExecutionContext) {
    const report = await callTalosTool('get_last_security_report', {}, ctx);

    return {
      uri,
      report,
    };
  }
}
